baseurl: '/'

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
#  - scope:
#      path: ""
#      type: "kotlin-api-calling"
#    values:
#      layout: "tutorial"
#  - scope:
#      path: ""
#      type: "kotlin-ws"
#    values:
#      layout: "tutorial"
#  - scope:
#      path: ""
#      type: "tools"
#    values:
#      layout: "tutorial"
#  - scope:
#      path: ""
#      type: "vue"
#    values:
#      layout: "tutorial"
#  - scope:
#      path: ""
#      type: "updates"
#    values:
#      layout: "tutorial"
theme: minima
title: DevOps at BYU

collections_dir: content

#collections:
#  tools:
#    output: true
#    order: 1
#  kotlin-ws:
#    output: true
#    order: 2
#  kotlin-api-calling:
#    output: true
#    order: 3
#  vue:
#    output: true
#    order: 4
#  updates:
#    output: true
#    order: 5

plugins:
  - jekyll-relative-links

markdown: kramdown

relative_links:
  enabled:     true
  collections: true
